# docker-compose.dev.yml
services:
  # ─────────────────────────────────────────────────────────────
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: chirpstack_timescaledb_dev
    restart: always
    environment:
      POSTGRES_DB: sensordata
      POSTGRES_USER: sensoruser
      POSTGRES_PASSWORD: sensorpass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - timescaledb_data_dev:/var/lib/postgresql/data
    ports:
      - "15432:5432"          # ← PUEDES CAMBIARLO O ELIMINARLO

  # ─────────────────────────────────────────────────────────────
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto_dev
    restart: always
    ports:
      - "1884:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  # ─────────────────────────────────────────────────────────────
  app:
    build:
      context: .
    container_name: chirpstack_app_dev
    entrypoint: ["/app/entrypoint-dev.sh"]
    volumes:
      - .:/app                    # hot-reload
    env_file:
      - env.dev
    environment:
      DB_HOST: chirpstack_timescaledb_dev
      DB_PORT: 5432               # puerto interno del contenedor
      DB_USER: sensoruser
      DB_PASS: sensorpass
      DB_NAME: sensordata
      ENV: development
    ports:
      - "8999:8999"
    depends_on:
      timescaledb:
        condition: service_healthy
      mosquitto:
        condition: service_started

volumes:
  timescaledb_data_dev:
