services:
  listener_app:
    container_name: chirpstack_listener_app
    build:
      context: .
    restart: always
    env_file:
      - .env.production
    environment:
      # Mantén las variables visibles en docker inspect
      - MQTT_BROKER
      - MQTT_PORT
      - MQTT_CA
      - MQTT_CERT
      - MQTT_KEY
      - MQTT_TOPIC
      - MQTT_USER
      - MQTT_PASSWORD
    volumes:
      - ./logs:/var/log
    depends_on:
      - timescaledb
    command: python -m app.mqtt_client    # ← ejecuta solo el listener

  timescaledb:
    container_name: chirpstack_timescaledb
    image: timescale/timescaledb:latest-pg14
    restart: always
    env_file:
      - .env.production
    environment:
      POSTGRES_DB: sensordata
      POSTGRES_USER: sensoruser
      POSTGRES_PASSWORD: sensorpass
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "sensoruser", "-d", "sensordata"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - timescale_data:/var/lib/postgresql/data

volumes:
  timescale_data:
