# docker-compose.production.yml
services:
  chirpstack_timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: chirpstack_timescaledb
    restart: always
    env_file:
      - env.production
    healthcheck:
      # Usa $$ para que Compose no intente sustituir en el host
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - timescale_data:/var/lib/postgresql/data

  chirpstack_listener_app:
    build: .
    container_name: chirpstack_listener_app
    restart: always
    env_file:
      - env.production
    entrypoint: ["./entrypoint-prod.sh"]   # API + hilo MQTT
    depends_on:
      chirpstack_timescaledb:
        condition: service_healthy
    ports:
      - "8999:8999"
    volumes:
      - ./logs:/var/log                    # para ver /var/log/api.err.log

volumes:
  timescale_data:
